### ISSUE TITLE
Check Cover position

### ISSUE THREAD

**Issue by MPocke** [nicolasberthel/hass-becker-component#13]
Hey there, I configured my Becker Cover to HomeAssistant successfully. The question I have is, is there a way to configure specific positions (like tilt position). Also check if the cover is currently up or down. And if so, how to do it? Thanks a lot.

**Comment by nicolasberthel** [comment]
@MPocke it is not possible to get a feedback from the cover, so the check might be difficult. The only option to have a real feedback would be to add an additional sensor on your cover, and to use it in your automations.
For the moment the component only support 1 intermediate position, as you recognize it with the tilt position.

**Comment by nicolasberthel** [comment]
The only position to have a real feedback would be to add an additional sensor on your cover, and to use it in your automatons

**Comment by gschmidl** [comment]
I've finished the first bit, an automation that will store the open/close value of your cover in a variable named the same as the cover, but with "input_number" at the start instead of "cover."

You can just create the numbers as Helpers.

```
- id: "becker"
  alias: "Rollladen fahren"
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: cover
        service: open_cover
    - platform: event
      event_type: call_service
      event_data:
        domain: cover
        service: close_cover
  action:
    - service: input_number.set_value
      data:
        value: >
          {% if states("input_number." + trigger.event.data.service_data.entity_id.split(".")[-1]) | int == 0 %}
          100
          {% else %}
          0
          {% endif %}
      target:
        entity_id: '{{ "input_number." + trigger.event.data.service_data.entity_id.split(".")[-1] }}'
```

Next: figure out what card to use to read the current state from those variables.

**Comment by gschmidl** [comment]
@nicolasberthel it seems like if I try to add a value_template to even one of the covers, the whole thing fails and all cover.* are unavailable. Also, position_template, which would be the better choice here, does not seem to be available.
```
cover:
  - platform: becker
    covers:
      wz1:
        friendly_name: "Wohnzimmer links aussen"
        channel: "1"
        value_template: "{{ states('input_number.wohnzimmer_links_aussen') | float > 0 }}"
      wz2:
        friendly_name: "Wohnzimmer links innen"
        channel: "2"
      wz3:
        friendly_name: "Wohnzimmer rechts innen"
        channel: "3"
      wz4:
        friendly_name: "Wohnzimmer rechts aussen"
        channel: "4"
```

Found something in the log:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/becker/cover.py", line 92, in async_setup_platform
    entity_ids = extract_entities(device, "cover", None, templates)
  File "/config/custom_components/becker/__init__.py", line 37, in extract_entities
    template_entity_ids = template.extract_entities()
AttributeError: 'Template' object has no attribute 'extract_entities'
```
Apparently extract_entities was removed: https://developers.home-assistant.io/blog/2020/11/09/system-health-and-templates/
